complete -c nb -f
complete -c nb -n '__fish_use_subcommand' -a 'init' -d 'Create /opt/nanobrew/ directory tree'
complete -c nb -n '__fish_use_subcommand' -a 'install' -d 'Install packages'
complete -c nb -n '__fish_use_subcommand' -a 'remove' -d 'Uninstall packages'
complete -c nb -n '__fish_use_subcommand' -a 'list' -d 'List installed packages'
complete -c nb -n '__fish_use_subcommand' -a 'info' -d 'Show formula info'
complete -c nb -n '__fish_use_subcommand' -a 'search' -d 'Search for packages'
complete -c nb -n '__fish_use_subcommand' -a 'upgrade' -d 'Upgrade packages'
complete -c nb -n '__fish_use_subcommand' -a 'update' -d 'Self-update nanobrew'
complete -c nb -n '__fish_use_subcommand' -a 'doctor' -d 'Check installation health'
complete -c nb -n '__fish_use_subcommand' -a 'cleanup' -d 'Remove stale caches'
complete -c nb -n '__fish_use_subcommand' -a 'outdated' -d 'List outdated packages'
complete -c nb -n '__fish_use_subcommand' -a 'pin' -d 'Pin a package'
complete -c nb -n '__fish_use_subcommand' -a 'unpin' -d 'Unpin a package'
complete -c nb -n '__fish_use_subcommand' -a 'rollback' -d 'Rollback to previous version'
complete -c nb -n '__fish_use_subcommand' -a 'bundle' -d 'Export/import package lists'
complete -c nb -n '__fish_use_subcommand' -a 'deps' -d 'Show dependency tree'
complete -c nb -n '__fish_use_subcommand' -a 'services' -d 'Manage services'
complete -c nb -n '__fish_use_subcommand' -a 'completions' -d 'Generate shell completions'
complete -c nb -n '__fish_use_subcommand' -a 'help' -d 'Show help'
