theme = "Ayu Dark"
theme-dark = "Nord"
foreground = "#b3b1ad"
background = "#0a0e14"
palette-0 = "#01060e"
open-with-app = "Xcode|com.apple.dt.Xcode"

palette-1 = "#ea6c73"
palette-2 = "#91b362"
palette-3 = "#f9af4f"
palette-4 = "#53bdfa"
palette-5 = "#fae994"
palette-6 = "#90e1c6"
palette-7 = "#c7c7c7"
palette-8 = "#686868"
palette-9 = "#f07178"
palette-10 = "#c2d94c"
palette-11 = "#ffb454"
palette-12 = "#59c2ff"
palette-13 = "#ffee99"
palette-14 = "#95e6cb"
# palette-15 = "#eceff4" (reset to default)

# selection-foreground = "#2e3440" (reset to default)
# selection-background = "#e5e9f0" (reset to default)
# cursor-color = "#e5e9f0" (reset to default)
# cursor-text = "#2e3440" (reset to default)

# font-blending = "linear" (reset to default)

details-view = 'id="info"'
details-view = 'id="outline"'
details-view = 'id="git"'
details-view = 'id="files"'
details-view = 'id="pi" kind="tui" title="Pi" icon="otty" command="cd ${cwd} && pi"'

details-panel-width = 402

# global-hotkey-open-window = "cmd+shift+p" (reset to default)

keybind = "cmd+enter=new_tab"
keybind = "opt+h=focus_previous_pane"
keybind = "opt+l=focus_next_pane"
keybind = "ctrl+opt+h=focus_pane_left"
keybind = "ctrl+opt+l=focus_pane_right"
keybind = "cmd+o=unbind"
keybind = "cmd+shift+h=previous_tab"
keybind = "cmd+shift+l=next_tab"
keybind = "cmd+j=unbind"
keybind = "ctrl+opt+k=focus_pane_up"
keybind = "ctrl+opt+j=focus_pane_down"

window-layout = "tabs-top"

# auto-hide-tab-bar = "auto" (reset to default)

new-tab-position = "after-current"

# window-size = "frame" (reset to default)

font-family = "Maple Mono NF CN"

font-family-bold = "Maple Mono NF CN"

font-family-italic = "Maple Mono NF CN"

font-family-bold-italic = "Maple Mono NF CN"

cursor-style-blink = "always_on"

cursor-animation = "smooth"

font-thicken = true

# font-ligatures-alphabet = true (reset to default)
