background            #FCFCFC
foreground            #5C6166
cursor                #F29718
selection_background  #D1E4F4
selection_foreground  #5C6166

color0                #5C6166
color8                #939498
color1                #F07171
color9                #EC6A53
color2                #86B300
color10               #86B300
color3                #EBA400
color11               #FF9940
color4                #55B4D4
color12               #22A4E6
color5                #EC6A53
color13               #A37ACC
color6                #4CBF99
color14               #4CBF99
color7                #5C6166
color15               #8A9199
