background            #0B0E14
foreground            #BFBDB6
cursor                #E6B450
selection_background  #1C2433
selection_foreground  #BFBDB6

color0                #0B0E14
color8                #5A6673
color1                #F07178
color9                #ED834B
color2                #AAD94C
color10               #AAD94C
color3                #F0A33A
color11               #E6B450
color4                #39BAE6
color12               #59C2FF
color5                #ED834B
color13               #D2A6FF
color6                #95E6CB
color14               #95E6CB
color7                #BFBDB6
color15               #BFBDB6
